name: Tests

on: [push]

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu]
        python_version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 ac3es/ --show-source --statistics
          flake8 ac3es/ --count --exit-zero --statistics
      - name: Test code
        run: |
          python3 -m unittest discover -p tests